### ISSUE TITLE
 'https://chromedriver.storage.googleapis.com/96.0.4664.18/chromedriver_linux64.zip'  unzip the chromedriver to /usr/bin add the chromedriver path to the python Script line 117

### ISSUE THREAD

**Issue by vukvukova** [Tripo-5/Freebitcoin-Automation#1]
Hi,

When i unzip chromedriver there is nowehere any .y also not in the Code, can please exlpaine me what does you mean with adding location in line 117 ?

thx

VukVukovaaa

**Comment by Tripo-5** [comment]
Hi @vukvukova 
You will need to use the latest chromedriver, as for the adding the location depending on what system you use this varies.
Follow below for the location instructions. 

`browser = webdriver.Chrome(executable_path=r'/usr/bin/chromedriver') # change me to your chromedriver executable location`

`browser = webdriver.Chrome(executable_path=r'CHANGEME')` 

For Linux

`browser = webdriver.Chrome(executable_path=r'~/home/Desktop/chromedriver') # If chromedriver is extracted to your desktop`

For Windows 

`browser = webdriver.Chrome(executable_path=r'C:\Users\User\Desktop\chromedriver') # If Chromedriver is Extracted to the Desktop remember to change the content to suit your system profile. `


New Chromedriver for the bot to work. This is coinciding with Chrome version they need to both the Browser and the Chromedriver be updated.

https://chromedriver.storage.googleapis.com/index.html?path=103.0.5060.134/

Most recent version above as of todays date.

Regards
